# Build settings
markdown: kramdown
permalink: pretty


# Dependencies
markdown:         kramdown

# Permalinks
permalink:        pretty

# Setup
title:            "The Nimble Tents Toolkit"
tagline:
description:      "urgent responses for academic and cultural institutions"
host:    127.0.0.1
url: ""
baseurl: "/nimble-tents"
email:


layout: blog-post

# Custom vars
version:          2.0.0

# Organize pages
include: ["_pages"]

#i18n
languages: ["en", "es"]
